# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-Handle-Record
version:      0.06
version_from: lib/IO/Handle/Record.pm
installdirs:  site
requires:
    Class::Member:                 1.3
    Storable:                      2.05
    Test::Deep:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
