--- #YAML:1.0
name:               IO-Handle-Record
version:            0.14
abstract:           IO::Handle extension to pass perl data structures
author:
    - Torsten Foertsch <torsten.foertsch@gmx.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Member:  1.3
    Storable:       2.05
    Test::Deep:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
